# just a handy way to try out different node versions

cmm:
    image: node:4
    volumes:
        - ./src:/app/src
        - ./test:/app/test
        - ./package.json:/app/package.json
    command: sleep 1000000000
